#!/bin/bash

#
# Copyright (c) 2025 AshokShau.
# TgMusicBot is an open-source Telegram music bot licensed under AGPL-3.0.
# All rights reserved where applicable.
#
#

echo "Starting TgMusicBot..."

python3 -m src
